#!/usr/bin/env escript
%%! -noshell -noinput
%% -*- mode: erlang;erlang-indent-level: 4;indent-tabs-mode: nil -*-
%% ex: ft=erlang ts=4 sw=4 et

-include_lib("kernel/include/file.hrl").

main(_) ->
    Filename = "erlangpl",
    Files = get_files(),

    case zip:create("mem", Files, [memory]) of
        {ok, {"mem", ZipBin}} ->
            Shebang = "#!/usr/bin/env escript\n",
            EmuArgs = "%%! -hidden\n",
            Script = iolist_to_binary([Shebang, EmuArgs, ZipBin]),
            case file:write_file(Filename, Script) of
                ok ->
                    ok;
                {error, WriteError} ->
                    io:format("Failed to write escript: ~p\n",
                           [WriteError])
            end;
        {error, ZipError} ->
            io:format("Failed to zip: ~p\n", [ZipError])
    end,

    {ok, #file_info{mode = Mode}} = file:read_file_info(Filename),
    ok = file:change_mode(Filename, Mode bor 8#00100).

get_files() ->
    %% find all directories in apps/ and deps/
    %% each directory represents an erlang application
    Apps = filelib:wildcard("{apps,deps}/*"),

    %% read contents of all .app and .beam files
    %% as well as contents of priv/ directories
    Fun = fun(Path, Acc) when Path == "apps/epl/ebin/erlangpl.beam" ->
                  %% escript requires us to put erlangpl.beam in top-level dir
                  [{"erlangpl.beam", file_contents(Path)} | Acc];
             (Path, Acc) ->
                  %% all other files will appear under application dir
                  %% e.g. {"epl/ebin/epl.app", "...<contents>..."}
                  Filename = filename:join(tl(filename:split(Path))),
                  [{Filename, file_contents(Path)} | Acc]
          end,

    %% include all compiled modules and the .app file
    Beams = [filelib:fold_files(Dir, "\\.app$|\\.beam$", true, Fun, [])
	     || Dir <- Apps],

    %% include all contents of the priv dirs
    %% except for .js.map files, which are heavy but unnecessary
    Privs = [filelib:fold_files(filename:join([Dir, "priv"]),
                                "^((?!\\.js\\.map).)*$", true, Fun, [])
	     || Dir <- Apps],

    lists:flatten([Beams, Privs]).

file_contents(Filename) ->
    {ok, Bin} = file:read_file(Filename),
    Bin.
